BIRDS = [
    'Abd al-Kuri Sparrow',
    'Abyssinian Nightjar',
    'Abyssinian Oriole',
    'Acadian Flycatcher',
    'Accentor',
    'Acorn Woodpecker',
    'Adelie Penguin',
    'Afghan Snowfinch',
    'African Barred Owlet',
    'African Black-headed Oriole',
    'African Broadbill',
    'African Emerald Cuckoo',
    'African Finfoot',
    'African Fish Eagle',
    'African Green Pigeon',
    'African Harrier-Hawk',
    'African Jacana',
    'African Openbill',
    'African Paradise-flycatcher',
    'African Penguin',
    'African Pygmy Goose',
    'Albatross',
    'Alpine Accentor',
    'Alpine Chough',
    'Alpine Swift',
    'American Crow',
    'American Dipper',
    'American Golden Plover',
    'American Goldfinch',
    'American Kestrel',
    'American Redstart',
    'American Robin',
    'American White Pelican',
    'American Wigeon',
    'American Woodcock',
    'Andean Cock-of-the-rock',
    'Andean Condor',
    'Andean Flamingo',
    'Andean Goose',
    'Anhinga',
    'Anna’s Hummingbird',
    'Antarctic Petrel',
    'Antarctic Prion',
    'Antarctic Tern',
    'Antenna Satinbird',
    'Apostlebird',
    'Arabian Golden Sparrow',
    'Arctic Tern',
    'Arctic Warbler',
    'Ashy Storm Petrel',
    'Asian Fairy Bluebird',
    'Asian Glossy Starling',
    'Asian Koel',
    'Asian Paradise-flycatcher',
    'Atlantic Puffin',
    'Auk',
    'Austral Thrush',
    'Australasian Gannet',
    'Australasian Grebe',
    'Australian Brush-turkey',
    'Australian Bustard',
    'Australian King Parrot',
    'Australian Logrunner',
    'Australian Magpie',
    'Australian Masked Owl',
    'Australian Owlet-nightjar',
    'Australian Pelican',
    'Australian Pratincole',
    'Australian Reed-warbler',
    'Australian White Ibis',
    'Avocet',
    'Aztec Thrush',
    'Azure-winged Magpie',
    'Bachman’s Sparrow',
    'Baillon’s Crake',
    'Bald Eagle',
    'Bali Myna',
    'Baltimore Oriole',
    'Bananaquit',
    'Band-tailed Manakin',
    'Banded Stilt',
    'Bar-headed Goose',
    'Bar-tailed Godwit',
    'Bar-throated Apalis',
    'Bare-eyed White-eye',
    'Bare-throated Bellbird',
    'Barn Owl',
    'Barn Swallow',
    'Barnacle Goose',
    'Barred Antshrike',
    'Barred Cuckoo-shrike',
    'Barred Fruiteater',
    'Barred Owl',
    'Barred Warbler',
    'Bateleur',
    'Beach Stone-curlew',
    'Bearded Barbet',
    'Bearded Reedling',
    'Bearded Vulture',
    'Bee Hummingbird',
    'Bee-eater',
    'Besra',
    'Bewick’s Wren',
    'Bicoloured Antbird',
    'Bittern',
    'Black Bulbul',
    'Black Guillemot',
    'Black Kite',
    'Black Oystercatcher',
    'Black Redstart',
    'Black Scoter',
    'Black Skimmer',
    'Black Swan',
    'Black Tern',
    'Black vulture',
    'Black Wheatear',
    'Black Woodpecker',
    'Black-and-white Hawk-Eagle',
    'Black-and-white Warbler',
    'Black-bellied Storm Petrel',
    'Black-browed Albatross',
    'Black-capped Chickadee',
    'Black-capped Donacobius',
    'Black-capped Gnatcatcher',
    'Black-chested Snake Eagle',
    'Black-collared Barbet',
    'Black-collared Hawk',
    'Black-crowned Night Heron',
    'Black-crowned Tchagra',
    'Black-faced Antthrush',
    'Black-faced Cuckoo-shrike',
    'Black-faced Ibis',
    'Black-faced Monarch',
    'Black-fronted Nunbird',
    'Black-headed Duck',
    'Black-legged Kittiwake',
    'Black-naped Monarch',
    'Black-rumped Flameback',
    'Black-rumped Waxbill',
    'Black-spotted Barbet',
    'Black-spotted Bare-eye',
    'Black-tailed Gnatcatcher',
    'Black-tailed Trainbearer',
    'Black-throated Diver',
    'Black-throated Trogon',
    'Black-winged Snowfinch',
    'Black-winged Stilt',
    'Blackbird',
    'Blackburnian Warbler',
    'Blackcap',
    'Blackish Cinclodes',
    'Blacksmith Plover',
    'Blakiston’s Fish-owl',
    'Blood Pheasant',
    'Blue Duck',
    'Blue Grosbeak',
    'Blue Jay',
    'Blue Manakin',
    'Blue Mockingbird',
    'Blue Tit',
    'Blue Vanga',
    'Blue Whistling-thrush',
    'Blue-and-White Flycatcher',
    'Blue-and-white Swallow',
    'Blue-and-yellow Macaw',
    'Blue-crowned Parakeet',
    'Blue-crowned Racquet-tail',
    'Blue-faced Honeyeater',
    'Blue-faced Parrotfinch',
    'Blue-footed Booby',
    'Blue-gray Gnatcatcher',
    'Blue-headed Parrot',
    'Blue-headed Quail-Dove',
    'Blue-naped Chlorophonia',
    'Blue-naped Mousebird',
    'Blue-naped Parrot',
    'Blue-rumped Parrot',
    'Blue-winged Macaw',
    'Blue-winged Minla',
    'Blue-winged Mountain-tanager',
    'Blue-winged Parrotlet',
    'Blue-winged Pitta',
    'Bluebonnet',
    'Bluetail',
    'Bluethroat',
    'Bluish-fronted Jacamar',
    'Blyth’s Tragopan',
    'Boat-billed Flycatcher',
    'Boat-billed Heron',
    'Bobolink',
    'Bohemian Waxwing',
    'Bokmakierie',
    'Bornean Bristlehead',
    'Brahminy Kite',
    'Brambling',
    'Brent Goose',
    'Brewer’s Blackbird',
    'Brolga',
    'Bronze Sunbird',
    'Brown Creeper',
    'Brown Kiwi',
    'Brown Noddy',
    'Brown Pelican',
    'Brown Songlark',
    'Brown Teal',
    'Brown Thornbill',
    'Brown Thrasher',
    'Brown Tinamou',
    'Brown Treecreeper',
    'Brown Trembler',
    'Brown-headed Cowbird',
    'Brown-throated Wattle-eye',
    'Brush Cuckoo',
    'Budgerigar',
    'Buff-banded Rail',
    'Buff-throated Saltator',
    'Bufflehead',
    'Bullfinch',
    'Bullock’s Oriole',
    'Bunting',
    'Burrowing Owl',
    'Burrowing Parakeet',
    'Bush Petronia',
    'Bushtit',
    'Bustard',
    'Buzzard',
    'Cackling Goose',
    'Cactus Wren',
    'Caerulean Paradise-flycatcher',
    'Cahow',
    'Calandra Lark',
    'California Condor',
    'California Gnatcatcher',
    'California Quail',
    'Campo Flicker',
    'Canada Goose',
    'Canvasback',
    'Canyon Canastero',
    'Canyon Wren',
    'Cape Batis',
    'Cape Grassbird',
    'Cape Longclaw',
    'Cape Petrel',
    'Cape Rockjumper',
    'Cape Sparrow',
    'Cape Spurfowl',
    'Cape Sugarbird',
    'Cape Weaver',
    'Cape White-eye',
    'Capercaillie',
    'Cardinal Woodpecker',
    'Carolina Wren',
    'Carrion Crow',
    'Caspian Tern',
    'Cassin’s Finch',
    'Catbird',
    'Cattle Egret',
    'Cattle Tyrant',
    'Cave Swiftlet',
    'Cedar Waxwing',
    'Cetti’s Warbler',
    'Ceylon Junglefowl',
    'Chaffinch',
    'Channel-billed Cuckoo',
    'Chapada Flycatcher',
    'Chestnut Bulbul',
    'Chestnut Munia',
    'Chestnut Sparrow',
    'Chestnut Woodpecker',
    'Chestnut-backed Jewel-babbler',
    'Chestnut-cheeked Starling',
    'Chestnut-eared Aracari',
    'Chicken',
    'Chiffchaff',
    'Chilean Flamingo',
    'Chilean Tinamou',
    'Chimney Swift',
    'Chipping Sparrow',
    'Chough',
    'Christmas Frigatebird',
    'Chuck-will’s-widow',
    'Chukar Partridge',
    'Cicadabird',
    'Cinereous Conebill',
    'Cinereous Tinamou',
    'Cinnamon Tanager',
    'Cisticola',
    'Clapper Lark',
    'Clark’s Grebe',
    'Clark’s Nutcracker',
    'Clay-colored Robin',
    'Cliff Flycatcher',
    'Cliff Swallow',
    'Coal Tit',
    'Cockatiel',
    'Collared Aracari',
    'Collared Inca',
    'Collared Pratincole',
    'Common Babbler',
    'Common Black Hawk',
    'Common Black-headed Gull',
    'Common Blackbird',
    'Common Bronzewing',
    'Common Buzzard',
    'Common Chaffinch',
    'Common Chiffchaff',
    'Common Crane',
    'Common Cuckoo',
    'Common Diving Petrel',
    'Common Goldeneye',
    'Common Grackle',
    'Common Hawk-Cuckoo',
    'Common Iora',
    'Common Kestrel',
    'Common Merganser',
    'Common Miner',
    'Common Moorhen',
    'Common Myna',
    'Common Nighthawk',
    'Common Ostrich',
    'Common Pheasant',
    'Common Pigeon',
    'Common Pochard',
    'Common Poorwill',
    'Common Potoo',
    'Common Quail',
    'Common Redpoll',
    'Common Redshank',
    'Common Redstart',
    'Common Rock Thrush',
    'Common Shelduck',
    'Common Snipe',
    'Common Starling',
    'Common Sunbird-asity',
    'Common Swift',
    'Common Tailorbird',
    'Common Teal',
    'Common Tody-flycatcher',
    'Common Yellowthroat',
    'Congo Peafowl',
    'Cook’s Petrel',
    'Cooper’s Hawk',
    'Coot',
    'Coppersmith Barbet',
    'Cormorant',
    'Corn Crake',
    'Corncrake',
    'Cory’s Shearwater',
    'Courser',
    'Cowbird',
    'Crab Plover',
    'Crake',
    'Crane',
    'Crane Hawk',
    'Cream-coloured Courser',
    'Crested Bellbird',
    'Crested Drongo',
    'Crested Eagle',
    'Crested Gallito',
    'Crested Guan',
    'Crested Jay',
    'Crested Lark',
    'Crested Oropendola',
    'Crested Owl',
    'Crested Partridge',
    'Crested Serpent Eagle',
    'Crested Shrike-tit',
    'Crested Tit',
    'Crested White-eye',
    'Crimson Chat',
    'Crimson Rosella',
    'Crimson Sunbird',
    'Crimson Topaz',
    'Crimson-breasted Flowerpecker',
    'Crossbill',
    'Crow',
    'Crowned Eagle',
    'Crowned Sandgrouse',
    'Cuban Amazon',
    'Cuban Trogon',
    'Cuckoo',
    'Curlew',
    'Curve-billed Thrasher',
    'Cut-throat Finch',
    'Dark Chanting Goshawk',
    'Dark-eyed Junco',
    'Dartford Warbler',
    'Dead Sea Sparrow',
    'Desert Finch',
    'Desert Sparrow',
    'Diamond Dove',
    'Dickcissel',
    'Dipper',
    'Diver',
    'Doherty’s Bushshrike',
    'Dotterel',
    'Double-crested Cormorant',
    'Double-eyed Fig-parrot',
    'Dove',
    'Dowitcher',
    'Downy Woodpecker',
    'Duck',
    'Dunlin',
    'Dunnock',
    'Dusky-legged Guan',
    'Dwarf Cassowary',
    'Eagle',
    'Eared Pygmy-tyrant',
    'Eastern Bluebird',
    'Eastern Bristlebird',
    'Eastern Imperial Eagle',
    'Eastern Kingbird',
    'Eastern Long-tailed Hermit',
    'Eastern Meadowlark',
    'Eastern Phoebe',
    'Eastern Screech Owl',
    'Eastern Spinebill',
    'Eastern Whipbird',
    'Eastern Yellow Robin',
    'Eclectus Parrot',
    'Ecuadorian Hillstar',
    'Edible-nest Swiftlet',
    'Egret',
    'Egyptian Goose',
    'Egyptian Plover',
    'Egyptian Vulture',
    'Eider',
    'Elegant Crested Tinamou',
    'Elegant Trogon',
    'Elepaio',
    'Elf Owl',
    'Elliot’s Pheasant',
    'Emerald Toucanet',
    'Emperor Penguin',
    'Emu',
    'Eurasian Bittern',
    'Eurasian Bullfinch',
    'Eurasian Collared Dove',
    'Eurasian Coot',
    'Eurasian Curlew',
    'Eurasian Eagle-owl',
    'Eurasian Hobby',
    'Eurasian Jay',
    'Eurasian Nuthatch',
    'Eurasian Oystercatcher',
    'Eurasian Reed Warbler',
    'Eurasian Scops-owl',
    'Eurasian Sparrowhawk',
    'Eurasian Spoonbill',
    'Eurasian Stone-curlew',
    'Eurasian Three-toed Woodpecker',
    'Eurasian Tree Sparrow',
    'Eurasian Treecreeper',
    'Eurasian Wryneck',
    'European Golden Plover',
    'European Goldfinch',
    'European Green Woodpecker',
    'European Greenfinch',
    'European Honey Buzzard',
    'European Magpie',
    'European Nightjar',
    'European Penduline Tit',
    'European Pied Flycatcher',
    'European Robin',
    'European Shag',
    'European Stonechat',
    'European Storm Petrel',
    'European Turtle Dove',
    'Evening Grosbeak',
    'Fairy Penguin',
    'Fairy Prion',
    'Falcon',
    'Fan-tailed Berrypecker',
    'Fernwren',
    'Ferruginous Antbird',
    'Ferruginous Hawk',
    'Ferruginous Pygmy Owl',
    'Fieldfare',
    'Fiery-billed Aracari',
    'Figbird',
    'Finch',
    'Fire-tufted Barbet',
    'Firecrest',
    'Firewood-gatherer',
    'Fischer’s Turaco',
    'Flame Robin',
    'Flightless Cormorant',
    'Flycatcher',
    'Fox Sparrow',
    'Frigatebird',
    'Frilled Coquette',
    'Fulmar',
    'Gadwall',
    'Galah',
    'Galápagos Hawk',
    'Galápagos Penguin',
    'Gallinule',
    'Gang-gang Cockatoo',
    'Gannet',
    'Garganey',
    'Gentoo Penguin',
    'Giant Coua',
    'Giant Hummingbird',
    'Gila Woodpecker',
    'Glossy Ibis',
    'Godwit',
    'Goldcrest',
    'Golden Bowerbird',
    'Golden Eagle',
    'Golden Myna',
    'Golden Nightjar',
    'Golden Oriole',
    'Golden Pheasant',
    'Golden Pipit',
    'Golden Whistler',
    'Golden-crowned Kinglet',
    'Golden-fronted Leafbird',
    'Golden-headed Cisticola',
    'Golden-olive Woodpecker',
    'Goldeneye',
    'Goldfinch',
    'Goliath Heron',
    'Goosander',
    'Goose',
    'Goshawk',
    'Gould’s Sunbird',
    'Gouldian Finch',
    'Graceful Prinia',
    'Grasshopper Buzzard',
    'Grasshopper Warbler',
    'Gray Catbird',
    'Great Antshrike',
    'Great Argus',
    'Great Auk',
    'Great Black-backed Gull',
    'Great Blue Heron',
    'Great Blue Turaco',
    'Great Bowerbird',
    'Great Bustard',
    'Great Cormorant',
    'Great Crested Flycatcher',
    'Great Crested Grebe',
    'Great Frigatebird',
    'Great Grey Owl',
    'Great Horned Owl',
    'Great Jacamar',
    'Great Kiskadee',
    'Great Northern Diver',
    'Great Skua',
    'Great Slaty Woodpecker',
    'Great Sparrow',
    'Great Spotted Cuckoo',
    'Great Spotted Woodpecker',
    'Great Tinamou',
    'Great White Pelican',
    'Greater Adjutant',
    'Greater Flameback',
    'Greater Flamingo',
    'Greater Honeyguide',
    'Greater Hoopoe-lark',
    'Greater Kestrel',
    'Greater Necklaced Laughingthrush',
    'Greater Painted Snipe',
    'Greater Rhea',
    'Greater Roadrunner',
    'Greater Scaup',
    'Greater Spotted Eagle',
    'Greater Striped Swallow',
    'Greater Vasa Parrot',
    'Greater White-fronted Goose',
    'Greater Yellowlegs',
    'Greater Yellownape',
    'Grebe',
    'Green Broadbill',
    'Green Catbird',
    'Green Cochoa',
    'Green Heron',
    'Green Honeycreeper',
    'Green Imperial Pigeon',
    'Green Junglefowl',
    'Green Magpie',
    'Green Turaco',
    'Green-backed Woodpecker',
    'Green-billed Toucan',
    'Green-breasted Pitta',
    'Green-headed Tanager',
    'Green-tailed Bristlebill',
    'Green-winged Pytilia',
    'Greenfinch',
    'Greenish Puffleg',
    'Greenshank',
    'Grey Crowned Crane',
    'Grey Fantail',
    'Grey Go-away-bird',
    'Grey Goshawk',
    'Grey Gull',
    'Grey Heron',
    'Grey Parrot',
    'Grey Partridge',
    'Grey Plover',
    'Grey Shrike-thrush',
    'Grey Wagtail',
    'Grey-backed Camaroptera',
    'Grey-crested Cachalote',
    'Grey-crowned Babbler',
    'Grey-headed Chickadee',
    'Grey-headed Lovebird',
    'Grey-hooded Flycatcher',
    'Greylag Goose',
    'Griffon Vulture',
    'Groove-billed Ani',
    'Groove-billed Toucanet',
    'Grosbeak',
    'Ground Woodpecker',
    'Grouse',
    'Guanay Cormorant',
    'Guianan Piculet',
    'Guillemot',
    'Guira Cuckoo',
    'Gull',
    'Gull-billed Tern',
    'Gyrfalcon',
    'Hairy Woodpecker',
    'Hammerkop',
    'Harlequin Duck',
    'Harpy Eagle',
    'Harrier',
    'Harris’ Hawk',
    'Hawaiian Goose',
    'Hawfinch',
    'Hazel Grouse',
    'Helmet Vanga',
    'Helmeted Guineafowl',
    'Helmeted Manakin',
    'Hermit Thrush',
    'Heron',
    'Herring Gull',
    'Hill Myna',
    'Hill Partridge',
    'Himalayan Monal',
    'Himalayan Snowcock',
    'Hoary-headed Grebe',
    'Hoatzin',
    'Hobby',
    'Hooded Oriole',
    'Hook-billed Vanga',
    'Hoopoe',
    'Horned Guan',
    'Horned Lark',
    'Horned Screamer',
    'Horsfield’s Bronze Cuckoo',
    'Houbara Bustard',
    'House Crow',
    'House Martin',
    'House Sparrow',
    'House Wren',
    'Hudsonian Godwit',
    'Hyacinth Macaw',
    'Hypocolius',
    'Iago Sparrow',
    'Ibis',
    'Ibisbill',
    'Icterine Warbler',
    'Iiwi',
    'Imperial Shag',
    'Inca Dove',
    'Inca Tern',
    'Indian Black Eagle',
    'Indian Peafowl',
    'Indian Pitta',
    'Indian Robin',
    'Indian Vulture',
    'Inland Plover',
    'Italian Sparrow',
    'Ivory Gull',
    'Izu Leaf-warbler',
    'Jabiru',
    'Jack Snipe',
    'Jackdaw',
    'Jackson’s Widowbird',
    'Jacky Winter',
    'Jacobin Cuckoo',
    'Jamaican Oriole',
    'Jamaican Owl',
    'Japanese Accentor',
    'Japanese Grosbeak',
    'Japanese Pygmy Woodpecker',
    'Japanese Robin',
    'Japanese Thrush',
    'Japanese White-eye',
    'Japanese Wood Pigeon',
    'Japanese Woodpecker',
    'Java Sparrow',
    'Jay',
    'Junco',
    'Jungle Bush Quail',
    'Kagu',
    'Kakapo',
    'Kea',
    'Keel-billed Toucan',
    'Kelp Gull',
    'Kentish Plover',
    'Kenya Sparrow',
    'Kestrel',
    'Key West Quail-Dove',
    'Killdeer',
    'King Bird of Paradise',
    'King Eider',
    'King Penguin',
    'King Vulture',
    'Kingfisher',
    'Kite',
    'Kittiwake',
    'Knot',
    'Kōkako',
    'Kordofan Sparrow',
    'Kori Bustard',
    'Lanner Falcon',
    'Lapland Longspur',
    'Lappet-faced Vulture',
    'Lapwing',
    'Large Ground-finch',
    'Large-billed Crow',
    'Lark',
    'Lark Bunting',
    'Laughing Falcon',
    'Laughing Gull',
    'Laysan Albatross',
    'Leach’s Storm Petrel',
    'Lesser Bird of Paradise',
    'Lesser Cuckoo',
    'Lesser Flamingo',
    'Lewin’s Honeyeater',
    'Lichtenstein’s Sandgrouse',
    'Lidth’s Jay',
    'Limpkin',
    'Lineated Woodpecker',
    'Linnet',
    'Little Auk',
    'Little Bittern',
    'Little Bustard',
    'Little Corella',
    'Little Egret',
    'Little Grassbird',
    'Little Grebe',
    'Little Owl',
    'Little Sparrowhawk',
    'Little Spotted Kiwi',
    'Little Tinamou',
    'Lizard Buzzard',
    'Loggerhead Shrike',
    'Long-billed Bernieria',
    'Long-billed Curlew',
    'Long-billed Gnatwren',
    'Long-eared Owl',
    'Long-legged Buzzard',
    'Long-tailed Broadbill',
    'Long-tailed Duck',
    'Long-tailed Minivet',
    'Long-tailed Skua',
    'Long-tailed Sylph',
    'Long-tailed Tit',
    'Long-tailed Tyrant',
    'Long-trained Nightjar',
    'Long-wattled Umbrellabird',
    'Long-whiskered Owlet',
    'Lovely Cotinga',
    'Luzon Bleeding-heart',
    'Macaroni Penguin',
    'Madagascar Blue Pigeon',
    'Magellanic Flightless Steamer Duck',
    'Magellanic Penguin',
    'Magellanic Plover',
    'Magpie',
    'Magpie Tanager',
    'Magpie-goose',
    'Magpie-lark',
    'Malachite Sunbird',
    'Maleo',
    'Mallard',
    'Malleefowl',
    'Mandarin Duck',
    'Manx Shearwater',
    'Marabou Stork',
    'Marbled Duck',
    'Martial Eagle',
    'Martin',
    'Masked Booby',
    'Masked Finfoot',
    'Masked Lapwing',
    'Masked Water-tyrant',
    'Masked Woodswallow',
    'Maui Parrotbill',
    'Meadow Pipit',
    'Merganser',
    'Merlin',
    'Mew Gull',
    'Mimic Honeyeater',
    'Mississippi Kite',
    'Mistle Thrush',
    'Mistletoebird',
    'Mockingbird',
    'Monk Parakeet',
    'Montezuma Quail',
    'Montserrat Oriole',
    'Moorhen',
    'Mountain Blackeye',
    'Mountain Bluebird',
    'Mountain Pygmy Owl',
    'Mountain White-eye',
    'Mourning Dove',
    'Moustached Antpitta',
    'Mulga Parrot',
    'Murrelet',
    'Muscovy Duck',
    'Musk Duck',
    'Musk Lorikeet',
    'Mute Swan',
    'Namaqua Dove',
    'Narina Trogon',
    'Needletail',
    'Nene',
    'New Holland Honeyeater',
    'New Zealand Bellbird',
    'New Zealand Pigeon',
    'New Zealand Pipit',
    'New Zealand Robin',
    'Nicobar Pigeon',
    'Nighthawk',
    'Nightingale',
    'Nightjar',
    'Noisy Friarbird',
    'Noisy Miner',
    'Noisy Pitta',
    'Northern Black Korhaan',
    'Northern Bobwhite',
    'Northern Cardinal',
    'Northern Crested Caracara',
    'Northern Crombec',
    'Northern Fiscal',
    'Northern Flicker',
    'Northern Fulmar',
    'Northern Gannet',
    'Northern Goshawk',
    'Northern Grey-headed Sparrow',
    'Northern Harrier',
    'Northern Hawk-Owl',
    'Northern Lapwing',
    'Northern Mockingbird',
    'Northern Oriole',
    'Northern Parula',
    'Northern Pintail',
    'Northern Raven',
    'Northern Saw-whet Owl',
    'Northern Shoveler',
    'Northern Waterthrush',
    'Northern Wheatear',
    'Nubian Woodpecker',
    'Nutcracker',
    'Nuthatch',
    'Nuthatch Vanga',
    'Ocellated Antbird',
    'Ochre-breasted Foliage-gleaner',
    'Ochre-collared Piculet',
    'Oilbird',
    'Okinawa Rail',
    'Olivaceous Warbler',
    'Olivaceous Woodcreeper',
    'Olive-backed Sunbird',
    'Orange Oriole',
    'Orange-backed Woodpecker',
    'Orange-breasted Waxbill',
    'Orange-crowned Fairy-wren',
    'Orange-headed Thrush',
    'Orchard Oriole',
    'Oriental Magpie Robin',
    'Oriental White-eye',
    'Orinoco Goose',
    'Oriole',
    'Osprey',
    'Ouzel',
    'Ovenbird',
    'Owl',
    'Oystercatcher',
    'Pacific-slope Flycatcher',
    'Paddyfield Warbler',
    'Painted Bunting',
    'Painted Finch',
    'Palawan Peacock-Pheasant',
    'Pale-breasted Illadopsis',
    'Pale-winged Trumpeter',
    'Pallas’ Rosefinch',
    'Pallid Swift',
    'Palm Cockatoo',
    'Palm-nut Vulture',
    'Palmchat',
    'Papuan Hawk Owl',
    'Papuan Lorikeet',
    'Paradise Riflebird',
    'Paradise Whydah',
    'Parakeet',
    'Parasitic Skua',
    'Parrot-billed Sparrow',
    'Partridge',
    'Parula',
    'Pauraque',
    'Peach-fronted Parakeet',
    'Pel’s Fishing-owl',
    'Pere David’s Snowfinch',
    'Peregrine Falcon',
    'Peruvian Booby',
    'Petrel',
    'Phalarope',
    'Pheasant',
    'Pheasant Coucal',
    'Pheasant Cuckoo',
    'Pheasant-tailed Jacana',
    'Philippine Eagle',
    'Philippine Hawk-Eagle',
    'Phoebe',
    'Piapiac',
    'Pied Avocet',
    'Pied Bushchat',
    'Pied Butcherbird',
    'Pied Crow',
    'Pied Currawong',
    'Pied Harrier',
    'Pied Monarch',
    'Pigeon',
    'Pilotbird',
    'Pin-tailed Manakin',
    'Pin-tailed Sandgrouse',
    'Pin-tailed Whydah',
    'Pine Grosbeak',
    'Pine Siskin',
    'Pink Pigeon',
    'Pink-eared Duck',
    'Pink-throated Twinspot',
    'Pintail',
    'Pinyon Jay',
    'Pipit',
    'Plain Chachalaca',
    'Plain Xenops',
    'Plain-backed Snowfinch',
    'Plain-backed Sparrow',
    'Plain-brown Woodcreeper',
    'Planalto Hermit',
    'Planalto Woodcreeper',
    'Plate-billed Mountain Toucan',
    'Plover',
    'Plovercrest',
    'Plum-headed Parakeet',
    'Plumbeous Hawk',
    'Pochard',
    'Prairie Falcon',
    'Pratincole',
    'Prothonotary Warbler',
    'Ptarmigan',
    'Puffin',
    'Purple Gallinule',
    'Purple Grenadier',
    'Purple Martin',
    'Purple Sunbird',
    'Purple Swamphen',
    'Purple-crested Turaco',
    'Purple-rumped Sunbird',
    'Pygmy Cormorant',
    'Pygmy Falcon',
    'Pygmy Sunbird',
    'Pygmy Swift',
    'Quail',
    'Quail-plover',
    'Raggiana Bird of Paradise',
    'Rail',
    'Rainbow Lorikeet',
    'Raven',
    'Razorbill',
    'Red Crossbill',
    'Red Junglefowl',
    'Red Kite',
    'Red Knot',
    'Red Lory',
    'Red Wattlebird',
    'Red-and-green Macaw',
    'Red-and-yellow Barbet',
    'Red-backed Shrike',
    'Red-bellied Pitta',
    'Red-billed Blue Magpie',
    'Red-billed Chough',
    'Red-billed Firefinch',
    'Red-billed Quelea',
    'Red-billed Scythebill',
    'Red-billed Streamertail',
    'Red-billed Tropicbird',
    'Red-breasted Flycatcher',
    'Red-breasted Goose',
    'Red-breasted Nuthatch',
    'Red-breasted Sapsucker',
    'Red-browed Finch',
    'Red-capped Parrot',
    'Red-crested Cardinal',
    'Red-crested Turaco',
    'Red-crowned Crane',
    'Red-crowned Parakeet',
    'Red-eyed Vireo',
    'Red-fan Parrot',
    'Red-headed',
    'Red-headed Woodpecker',
    'Red-legged Honeycreeper',
    'Red-legged Seriema',
    'Red-legged Thrush',
    'Red-necked Avocet',
    'Red-necked Phalarope',
    'Red-necked Tanager',
    'Red-rumped Parrot',
    'Red-shouldered Cuckoo-shrike',
    'Red-shouldered Hawk',
    'Red-shouldered Macaw',
    'Red-tailed Black Cockatoo',
    'Red-tailed Hawk',
    'Red-throated Alethe',
    'Red-throated Barbet',
    'Red-throated Diver',
    'Red-throated Pipit',
    'Red-whiskered Bulbul',
    'Red-winged Blackbird',
    'Red-winged Parrot',
    'Reddish-bellied Parakeet',
    'Redhead',
    'Redpoll',
    'Redshank',
    'Redstart',
    'Redwing',
    'Reed Bunting',
    'Regent Parrot',
    'Resplendent Quetzal',
    'Restless Flycatcher',
    'Rhinoceros Auklet',
    'Ribbon-tailed Astrapia',
    'Rifleman',
    'Ring Ouzel',
    'Ringed Plover',
    'Robin',
    'Rock',
    'Rock Parrot',
    'Rock Ptarmigan',
    'Rock Sparrow',
    'Rock Wren',
    'Rockhopper penguin',
    'Roller',
    'Rook',
    'Rose-breasted Grosbeak',
    'Rose-crowned Fruit-dove',
    'Rose-ringed Parakeet',
    'Roseate Spoonbill',
    'Roseate Tern',
    'Rosefinch',
    'Ross’s Gull',
    'Rosy Starling',
    'Rosy-faced Lovebird',
    'Royal Albatross',
    'Royal Flycatcher',
    'Ruby Topaz',
    'Ruby-throated Hummingbird',
    'Rubythroat',
    'Ruddy Duck',
    'Rueppell’s Warbler',
    'Rufescent Tiger-heron',
    'Ruff',
    'Ruffed Grouse',
    'Rufous Bristlebird',
    'Rufous Bush Robin',
    'Rufous Gnateater',
    'Rufous Hornero',
    'Rufous Piculet',
    'Rufous Scrubbird',
    'Rufous Vanga',
    'Rufous Whistler',
    'Rufous-bellied Niltava',
    'Rufous-browed Peppershrike',
    'Rufous-capped Babbler',
    'Rufous-crested Coquette',
    'Rufous-crowned Antpitta',
    'Rufous-headed Pygmy-tyrant',
    'Rufous-necked Snowfinch',
    'Rufous-tailed Jacamar',
    'Rufous-tailed Plantcutter',
    'Rufous-winged Fulvetta',
    'Rüppell’s Parrot',
    'Rüppell’s Vulture',
    'Russet Sparrow',
    'Rusty-backed Antwren',
    'Rusty-belted Tapaculo',
    'Rusty-breasted Nunlet',
    'Rusty-cheeked Scimitar-babbler',
    'Saddle-billed Stork',
    'Saddleback',
    'Saffron Finch',
    'Sage Sparrow',
    'Sage Thrasher',
    'Sage-grouse',
    'Sand Martin',
    'Sanderling',
    'Sandgrouse',
    'Sandhill Crane',
    'Sandpiper',
    'São Paulo Tyrannulet',
    'Sapphire-rumped Parrotlet',
    'Sapsucker',
    'Sarus Crane',
    'Satin Bowerbird',
    'Satyr Tragopan',
    'Savanna Hawk',
    'Saxaul Sparrow',
    'Scale-throated Hermit',
    'Scalloped Woodcreeper',
    'Scarlet Finch',
    'Scarlet Ibis',
    'Scarlet Macaw',
    'Scarlet Minivet',
    'Scarlet Tanager',
    'Scaup',
    'Scissor-tailed Flycatcher',
    'Scops Owl',
    'Scoter',
    'Scott’s Oriole',
    'Secretary Bird',
    'Sedge Warbler',
    'Sedge Wren',
    'Serin',
    'Shag',
    'Sharpbill',
    'Shearwater',
    'Shelduck',
    'Shelley’s Sparrow',
    'Shining Flycatcher',
    'Shoebill',
    'Short-billed Dowitcher',
    'Short-eared Owl',
    'Short-tailed Shearwater',
    'Shoveler',
    'Shrike',
    'Siberian Crane',
    'Siberian Jay',
    'Silktail',
    'Silky-tailed Nightjar',
    'Silver Oriole',
    'Silver-beaked Tanager',
    'Silver-breasted Broadbill',
    'Silver-eared Mesia',
    'Silvereye',
    'Sind Sparrow',
    'Siskin',
    'Six Plumed Bird of Paradise',
    'Skua',
    'Skylark',
    'Slaty Bristlefront',
    'Slaty-breasted Tinamou',
    'Slaty-headed Longbill',
    'Small Ground-finch',
    'Smew',
    'Snail Kite',
    'Snipe',
    'Snow Bunting',
    'Snow Goose',
    'Snow Petrel',
    'Snowy Cotinga',
    'Snowy Owl',
    'Snowy Sheathbill',
    'Sociable Weaver',
    'Socorro Mockingbird',
    'Socotra Sparrow',
    'Socotra Sunbird',
    'Sokoke Scops Owl',
    'Solitary Eagle',
    'Somali Sparrow',
    'Sombre Greenbul',
    'Song Sparrow',
    'Song Thrush',
    'Sooty Albatross',
    'Sooty Shearwater',
    'Sooty Tern',
    'Sora',
    'South Polar Skua',
    'Southern Boobook',
    'Southern Cassowary',
    'Southern Fiscal',
    'Southern Giant Petrel',
    'Southern Grey-headed Sparrow',
    'Southern Lapwing',
    'Southern Masked Weaver',
    'Southern Screamer',
    'Southern White-faced Owl',
    'Southern Whiteface',
    'Spanish Sparrow',
    'Sparrow',
    'Sparrowhawk',
    'Speckle-fronted Weaver',
    'Speckled Hummingbird',
    'Speckled Mousebird',
    'Speckled Pigeon',
    'Spectacled Monarch',
    'Spectacled Owl',
    'Spectacled Weaver',
    'Spike-heeled Lark',
    'Spinifex Pigeon',
    'Spinifexbird',
    'Spiny-cheeked Honeyeater',
    'Spix’s Macaw',
    'Spix’s Spinetail',
    'Splendid Fairy-wren',
    'Spoon-billed Sandpiper',
    'Spoonbill',
    'Spot-billed Toucanet',
    'Spotted Antbird',
    'Spotted Bowerbird',
    'Spotted Flycatcher',
    'Spotted Harrier',
    'Spotted Nutcracker',
    'Spotted Quail-thrush',
    'Spotted Sandpiper',
    'Spotted Towhee',
    'Spruce Grouse',
    'Spur-winged Goose',
    'Spur-winged Lapwing',
    'Squacco Heron',
    'Squamate Antbird',
    'Squirrel Cuckoo',
    'Standard-winged Nightjar',
    'Star-throated Antwren',
    'Starling',
    'Steller’s Jay',
    'Steller’s Sea Eagle',
    'Stilt',
    'Stint',
    'Stitchbird',
    'Stonechat',
    'Stork',
    'Storm-petrel',
    'Straw-headed Bulbul',
    'Streak-backed Oriole',
    'Streamer-tailed Tyrant',
    'Striated Grasswren',
    'Striated Heron',
    'Striated Pardalote',
    'Striated Yuhina',
    'Subdesert Mesite',
    'Sudan Golden Sparrow',
    'Sulphur-crested Cockatoo',
    'Sultan Tit',
    'Sunbittern',
    'Sungrebe',
    'Superb Bird of Paradise',
    'Superb Fairy-wren',
    'Superb Fruit-dove',
    'Superb Lyrebird',
    'Superb Parrot',
    'Superb Starling',
    'Swahili Sparrow',
    'Swainson’s Hawk',
    'Swainson’s Sparrow',
    'Swallow',
    'Swallow Tanager',
    'Swallow-tailed Cotinga',
    'Swallow-tailed Gull',
    'Swallow-tailed Hummingbird',
    'Swallow-tailed Kite',
    'Swallow-winged Puffbird',
    'Swan',
    'Swan Goose',
    'Swift',
    'Sword-billed Hummingbird',
    'Takahē',
    'Tanager',
    'Tattler',
    'Tawny Frogmouth',
    'Tawny Owl',
    'Teal',
    'Temminck’s Tragopan',
    'Tennessee Warbler',
    'Tern',
    'Thick-billed Euphonia',
    'Thick-billed Raven',
    'Thicket Tinamou',
    'Thorn-tailed Rayadito',
    'Thrasher',
    'Three-wattled Bellbird',
    'Thrush',
    'Thrush Nightingale',
    'Thrush-like Schiffornis',
    'Tit',
    'Toco Toucan',
    'Topknot Pigeon',
    'Towhee',
    'Tree Swallow',
    'Treecreeper',
    'Tristram’s Starling',
    'Tropical Gnatcatcher',
    'Tropical Kingbird',
    'Tropicbird',
    'Tufted Duck',
    'Tufted Titmouse',
    'Tui',
    'Tundra Swan',
    'Turkey Vulture',
    'Turnstone',
    'Turquoise-fronted Amazon',
    'Twelve-wired Bird of Paradise',
    'Twite',
    'Unicoloured Tapaculo',
    'Ural Owl',
    'Variable Seedeater',
    'Varied Lorikeet',
    'Varied Sittella',
    'Varied Tit',
    'Variegated Fairy-wren',
    'Veery',
    'Velvet Asity',
    'Verdin',
    'Vermilion Flycatcher',
    'Vernal Hanging Parrot',
    'Verreaux’s Eagle',
    'Verreaux’s Eagle-owl',
    'Versicoloured Emerald',
    'Victoria Crowned Pigeon',
    'Victoria’s Riflebird',
    'Vinous-throated Parrotbill',
    'Violet Sabrewing',
    'Violet-capped Woodnymph',
    'Violet-fronted Brilliant',
    'Vireo',
    'Virginia Rail',
    'Vulture',
    'Vulturine Guineafowl',
    'Vulturine Parrot',
    'Wagtail',
    'Wahlberg’s Eagle',
    'Wallcreeper',
    'Wandering Albatross',
    'Wandering Tattler',
    'Warbler',
    'Warbling Vireo',
    'Water Pipit',
    'Water Rail',
    'Waterfall Swift',
    'Waterthrush',
    'Wattled Starling',
    'Waxwing',
    'Wedge-tailed Eagle',
    'Weebill',
    'Welcome Swallow',
    'Western Bluebill',
    'Western Capercaillie',
    'Western Jackdaw',
    'Western Marsh Harrier',
    'Western Scrub-jay',
    'Western Wood Pewee',
    'Wheatear',
    'Whimbrel',
    'Whinchat',
    'Whip-poor-will',
    'White Hawk',
    'White Stork',
    'White Tern',
    'White-backed Swallow',
    'White-backed Vulture',
    'White-bearded Antshrike',
    'White-bellied Seedsnipe',
    'White-billed Buffalo Weaver',
    'White-browed Coucal',
    'White-browed Scrubwren',
    'White-browed Shortwing',
    'White-capped Water-redstart',
    'White-crested Tiger Heron',
    'White-crowned Forktail',
    'White-eared Puffbird',
    'White-eared Sibia',
    'White-eyed Foliage-gleaner',
    'White-faced Whistling Duck',
    'White-fronted Ground-tyrant',
    'White-headed Buffalo Weaver',
    'White-lored Gnatcatcher',
    'White-naped Honeyeater',
    'White-necked Picathartes',
    'White-necked Puffbird',
    'White-necked Raven',
    'White-plumed Antbird',
    'White-rumped Monjita',
    'White-rumped Needletail',
    'White-rumped Snowfinch',
    'White-shouldered Triller',
    'White-tailed Eagle',
    'White-tailed Robin',
    'White-tailed Tropicbird',
    'White-throated Dipper',
    'White-throated Fantail',
    'White-throated Gerygone',
    'White-throated Hummingbird',
    'White-throated Needletail',
    'White-throated Robin',
    'White-throated Spadebill',
    'White-throated Sparrow',
    'White-tipped Dove',
    'White-tipped Sicklebill',
    'White-tufted Grebe',
    'White-winged Chough',
    'White-winged Snowfinch',
    'Whitethroat',
    'Whooper Swan',
    'Whooping Crane',
    'Wigeon',
    'Wild Turkey',
    'Willie Wagtail',
    'Willow Ptarmigan',
    'Wilson’s Bird of Paradise',
    'Wilson’s Storm Petrel',
    'Winter Wren',
    'Wire-tailed Swallow',
    'Wompoo Fruit-dove',
    'Wood Duck',
    'Wood Pigeon',
    'Wood Stork',
    'Wood Thrush',
    'Wood Warbler',
    'Woodcock',
    'Woodlark',
    'Woodpecker',
    'Woodpecker Finch',
    'Woods-walking Goose',
    'Wren',
    'Wrenthrush',
    'Wrentit',
    'Wrybill',
    'Wryneck',
    'Yellow Oriole',
    'Yellow Warbler',
    'Yellow-bellied Elaenia',
    'Yellow-bellied Eremomela',
    'Yellow-bellied Flycatcher',
    'Yellow-bellied Sapsucker',
    'Yellow-billed Oxpecker',
    'Yellow-billed Shrike',
    'Yellow-billed Stork',
    'Yellow-breasted Boatbill',
    'Yellow-breasted Chat',
    'Yellow-browed Woodpecker',
    'Yellow-chevroned Parakeet',
    'Yellow-crowned Amazon',
    'Yellow-eyed Penguin',
    'Yellow-faced Grassquit',
    'Yellow-faced Honeyeater',
    'Yellow-fronted Tinkerbird',
    'Yellow-fronted Woodpecker',
    'Yellow-headed Caracara',
    'Yellow-knobbed Curassow',
    'Yellow-legged Buttonquail',
    'Yellow-rumped Cacique',
    'Yellow-rumped Thornbill',
    'Yellow-spotted Petronia',
    'Yellow-throated Miner',
    'Yellow-throated Petronia',
    'Yellow-throated Sparrow',
    'Yellow-throated Vireo',
    'Yellowhammer',
    'Yellowlegs',
    'Yellowthroat',
    'Zapata Sparrow',
    'Zebra Finch',
    'Zitting Cisticola',
    'Zone-tailed Hawk',
]

ADJECTIVES = [
    'Adorable',
    'Beautiful',
    'Elegant',
    'Fancy',
    'Glamorous',
    'Handsome',
    'Long',
    'Magnificent',
    'Quaint',
    'Sparkling',
    'Ugliest',
    'Unsightly',
    'Wide-eyed',
    'Brave',
    'Delightful',
    'Eager',
    'Faithful',
    'Gentle',
    'Happy',
    'Jolly',
    'Kind',
    'Lively',
    'Nice',
    'Obedient',
    'Proud',
    'Relieved',
    'Victorious',
    'Witty',
    'Zealous',
]
