#!/bin/bash

# script/bootstrap: Resolve all dependencies that the application requires to
#                   run.

function progress {
    echo "$(tput bold)$(tput setaf 4)==>$(tput sgr0) $(tput bold)$1$(tput sgr0)"
}

set -e

cd "$(dirname "$0")/.."

progress "Installing Python dependencies…"

# Warn the user about the dodgy py3-ortools package
echo "!! You may need to manually install ortools  !!"
echo "!! ortools is available here:                !!"
echo "!! https://pypi.python.org/pypi/py3-ortools/ !!"

if [ ! -d "venv" ]; then
    for pyvenv in pyvenv pyvenv-3.5 pyvenv-3.4; do
        if hash $pyvenv 2>/dev/null; then
            $pyvenv venv
            break
        fi
    done
fi

if [ ! -d "venv" ]; then
    echo "Virtual environment not created."
    exit 1
fi

source venv/bin/activate
venv/bin/pip install --quiet -r requirements.txt
deactivate
