#!/bin/bash

# script/update: Update application to run for its current checkout.

function progress {
    echo "$(tput bold)$(tput setaf 4)==>$(tput sgr0) $(tput bold)$1$(tput sgr0)"
}

set -e

cd "$(dirname "$0")/.."

script/bootstrap

progress "Updating DB…"

venv/bin/python manage.py migrate
