# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-02 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20160127_2018'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('time_slot', models.IntegerField()),
                ('manual', models.IntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Event')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scheduler.Job')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='scheduler.Volunteer')),
            ],
        ),
        migrations.RemoveField(
            model_name='manualscheduleentry',
            name='event',
        ),
        migrations.RemoveField(
            model_name='manualscheduleentry',
            name='job',
        ),
        migrations.RemoveField(
            model_name='manualscheduleentry',
            name='volunteer',
        ),
        migrations.DeleteModel(
            name='ManualScheduleEntry',
        ),
    ]
