# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 18:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_auto_20160213_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 2, 18, 27, 1, 271668, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='volunteer',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 3, 2, 18, 27, 12, 938520, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
